variables:
  POSTGRES_DB: thalia
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  # https://hub.docker.com/r/thalia/python-thalia/
  # https://github.com/thaliawww/python-thalia
  # Should get auto-updated with the official 'python' repository
  # Installs:
  #  - pip: coverage, poetry
  #  - apt: ghostscript
  PY37_IMAGE: thalia/python-thalia:3.7
  PY38_IMAGE: thalia/python-thalia:3.8
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"

stages:
  - test
  - deploy

codestyle:
  stage: test
  image: $PY37_IMAGE
  before_script:
    - poetry install --no-interaction
  script:
    - poetry run flake8 website
    # Check for obsolete translations in .po files (starting with `#~`).
    - cd website
    - grep --include="*.po" --files-with-matches --recursive "^#~" && exit 1 || echo "No obsolete translations found."
    # Check for untranslated strings in .po files
    - empty_strings=$(sed '$a\\' **/locale/nl/LC_MESSAGES/django.po | tac | sed '/^$/N;/\nmsgstr ""$/,/^msgid/!d' | tac)
    - empty_strings+=$(sed '$a\\' locale/nl/LC_MESSAGES/django.po | tac | sed '/^$/N;/\nmsgstr ""$/,/^msgid/!d' | tac)
    - if [[ $empty_strings ]]; then echo $empty_strings && exit 1; else echo "No untranslated strings found."; fi
    # Check for fuzzy translations in .po files
    - grep --include="*.po" --files-with-matches --recursive "#, fuzzy" && exit 1 || echo "No fuzzy translations found."

.djangotest: &djangotest
  stage: test
  services:
    - postgres:latest
  before_script:
    - git log -1
    - poetry install --no-interaction
  script:
    - cd website
    - poetry run python manage.py check
    - poetry run python manage.py templatecheck --project-only
    - poetry run python manage.py makemigrations --no-input --check --dry-run
    - poetry run python -Wall -mcoverage run manage.py test
    - coverage report --fail-under=100 --omit registrations/urls.py registrations/**.py
    - coverage report --fail-under=97.32 --omit payments/urls.py payments/**.py
    - coverage report

python37-django22:
  <<: *djangotest
  image: $PY37_IMAGE
  after_script:
    - cd website
    - coverage html --directory=covhtml --title="${CI_COMMIT_REF_SLUG} Coverage Report"
  artifacts:
    paths:
      - website/covhtml/

python38-django22:
  <<: *djangotest
  image: $PY38_IMAGE
  allow_failure: true

.sshsetup: &sshsetup
  before_script:
    - mkdir -p ~/.ssh
    - echo "$IVO_KNOWN_HOST" > ~/.ssh/known_hosts
    - echo "$COVERAGE_DEPLOY_SSH_KEY" > ~/.ssh/id_coverage
    - echo "$DOCS_DEPLOY_SSH_KEY" > ~/.ssh/id_docs
    - chmod 0600 ~/.ssh/id_*
    - apt-get update
    - apt-get install -y openssh-client

coverage deploy:
  stage: deploy
  image: debian:stretch
  dependencies:
    - python37-django22
  environment:
    name: coverage/${CI_COMMIT_REF_NAME}
    url: https://coverage.technicie.nl/${CI_COMMIT_REF_SLUG}/
    on_stop: coverage remove
  <<: *sshsetup
  script:
    - |
      sftp -i ~/.ssh/id_coverage coveragewww@ivo.thalia.nu -b <<EOF
      -rm ${CI_COMMIT_REF_SLUG}/*
      -rmdir ${CI_COMMIT_REF_SLUG}
      put -r website/covhtml ${CI_COMMIT_REF_SLUG}
      EOF

coverage remove:
    stage: deploy
    when: manual
    image: debian:stretch
    environment:
        name: coverage/${CI_COMMIT_REF_NAME}
        action: stop
    variables:
        GIT_STRATEGY: none
    <<: *sshsetup
    script:
      - |
        sftp -i ~/.ssh/id_coverage coveragewww@ivo.thalia.nu -b <<EOF
        rm ${CI_COMMIT_REF_SLUG}/*
        rmdir ${CI_COMMIT_REF_SLUG}
        EOF

docs tests:
  stage: test
  image: $PY37_IMAGE
  before_script:
    # install django deps
    - poetry install --no-interaction --extras "docs"
  script:
    - echo "Building current docs"
    - cd docs
    - env -u GITLAB_CI poetry run make doctest
    - env -u GITLAB_CI poetry run sphinx-build -W . _build
    - echo "Checking if there are changes"
    - poetry run ./generate-apidocs.sh
    - git diff --exit-code
  artifacts:
    paths:
      - docs/_build

docs deploy:
  stage: deploy
  image: debian:stretch
  dependencies:
    - docs tests
  environment:
    name: docs/${CI_COMMIT_REF_NAME}
    url: https://docs.technicie.nl/${CI_COMMIT_REF_SLUG}/
    on_stop: docs remove
  <<: *sshsetup
  script:
    - |
      sftp -i ~/.ssh/id_docs docswww@ivo.thalia.nu -b <<EOF
      -rm ${CI_COMMIT_REF_SLUG}/*/*
      -rm ${CI_COMMIT_REF_SLUG}/*
      -rmdir ${CI_COMMIT_REF_SLUG}/_images
      -rmdir ${CI_COMMIT_REF_SLUG}/_modules
      -rmdir ${CI_COMMIT_REF_SLUG}/_sources
      -rmdir ${CI_COMMIT_REF_SLUG}/_static
      -rmdir ${CI_COMMIT_REF_SLUG}/doctest
      -rmdir ${CI_COMMIT_REF_SLUG}/doctrees
      -rmdir ${CI_COMMIT_REF_SLUG}
      -mkdir ${CI_COMMIT_REF_SLUG}
      put -r docs/_build/* ${CI_COMMIT_REF_SLUG}
      EOF

docs remove:
  stage: deploy
  when: manual
  image: debian:stretch
  environment:
    name: docs/${CI_COMMIT_REF_NAME}
    action: stop
  variables:
    GIT_STRATEGY: none
  <<: *sshsetup
  script:
    - |
      sftp -i ~/.ssh/id_docs docswww@ivo.thalia.nu -b <<EOF
      rm ${CI_COMMIT_REF_SLUG}/*/*
      rm ${CI_COMMIT_REF_SLUG}/*
      rmdir ${CI_COMMIT_REF_SLUG}/_images
      rmdir ${CI_COMMIT_REF_SLUG}/_modules
      rmdir ${CI_COMMIT_REF_SLUG}/_sources
      rmdir ${CI_COMMIT_REF_SLUG}/_static
      rmdir ${CI_COMMIT_REF_SLUG}/doctest
      rmdir ${CI_COMMIT_REF_SLUG}/doctrees
      rmdir ${CI_COMMIT_REF_SLUG}
      EOF

build docker image:
  stage: test
  services:
    - docker:dind
  image: thalia/docker-compose
  tags:
    - docker
  except:
    - tags
  before_script:
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username thaliawww --password-stdin registry.hub.docker.com
  script:
    - docker-compose config -q
    - docker-compose build --build-arg install_dev_requirements=$DEV_REQUIREMENTS --build-arg source_commit=$(git rev-parse HEAD) web
    - docker tag $DOCKER_LATEST $DOCKER_TAG
    - docker push $DOCKER_TAG
  variables:
    DEV_REQUIREMENTS: 1
    DOCKER_LATEST: registry.hub.docker.com/thalia/concrexit:latest
    DOCKER_TAG: registry.hub.docker.com/thalia/concrexit:$CI_COMMIT_SHA

.reviewsetup:
  when: manual
  image: python:latest
  before_script:
    - apt-get update
    - apt-get install -y jq
    - pip install awscli
    - >-
      instanceids=$(
      aws --region eu-west-1 ec2 describe-instances
      --filters "Name=tag:Name,Values=concrexit-review-${CI_COMMIT_REF_SLUG}"
      | jq --raw-output '.Reservations|map(.Instances[0].InstanceId)|join(" ")'
      )
    - aws --region eu-west-1 ec2 terminate-instances --instance-ids ${instanceids} || true

review:
  stage: deploy
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    url: https://${CI_COMMIT_REF_SLUG}.review.technicie.nl/
    on_stop: review remove
  extends: .reviewsetup
  script:
    - username=$(head /dev/urandom | tr -dc 'a-z' | head -c 10)
    - password=$(head /dev/urandom | tr -dc 'a-zA-Z' | head -c 32)
    - echo -e "When the deployment is done, you can login with:\n$username\n$password"
    - >-
      sed -i -e "s/@version@/$CI_COMMIT_SHA/g"
      -e "s/@username@/$username/g"
      -e "s/@password@/$password/g"
      ./resources/ec2-bootstrap.sh
    - >-
      instanceid=$(
      aws --region eu-west-1 ec2 run-instances
      --count 1
      --instance-type t2.micro
      --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=concrexit-review-${CI_COMMIT_REF_SLUG}}]"
      --launch-template LaunchTemplateId=lt-03762fc23450c2471,Version=1
      --user-data file://resources/ec2-bootstrap.sh
      | jq --raw-output '.Instances[0].InstanceId'
      )
    - aws --region eu-west-1 ec2 wait instance-running --instance-ids ${instanceid}
    - ipaddress=$(aws --region eu-west-1 ec2 describe-instances --instance-ids ${instanceid} | jq --raw-output '.Reservations[0].Instances[0].PublicIpAddress')
    - |
      cat > add-record.json <<EOF
      {
        "Comment": "CREATE review deployment record",
        "Changes": [
          {
            "Action": "CREATE",
            "ResourceRecordSet": {
              "Name": "${CI_COMMIT_REF_SLUG}.review.technicie.nl.reviewhost",
              "Type": "A",
              "TTL": 10,
              "ResourceRecords": [{"Value": "${ipaddress}"}]
            }
          }
        ]

      }
      EOF
    - |
      cat > change-record.json <<EOF
      {
        "Comment": "CHANGE review deployment record",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "${CI_COMMIT_REF_SLUG}.review.technicie.nl.reviewhost",
              "Type": "A",
              "TTL": 10,
              "ResourceRecords": [{"Value": "${ipaddress}"}]
            }
          }
        ]
      }
      EOF
    - >-
      changeinfoid=$(
      (
      aws --region eu-west-1 route53 change-resource-record-sets
      --hosted-zone-id Z072013523EW763CDQ8K4
      --change-batch file://add-record.json
      ||
      aws --region eu-west-1 route53 change-resource-record-sets
      --hosted-zone-id Z072013523EW763CDQ8K4
      --change-batch file://change-record.json
      )
      | jq --raw-output '.ChangeInfo.Id'
      )
    - aws --region eu-west-1 route53 wait resource-record-sets-changed --id ${changeinfoid}

review remove:
  stage: deploy
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    action: stop
  variables:
    GIT_STRATEGY: none
  extends: .reviewsetup
  script:
    - >-
      aws --region eu-west-1 route53 list-resource-record-sets
      --hosted-zone-id Z072013523EW763CDQ8K4
      --query "ResourceRecordSets[?Name == '${CI_COMMIT_REF_SLUG}.review.technicie.nl.']"
      |
      jq '{"Comment": "DELETE review deployment record", "Changes": map({"Action": "DELETE", "ResourceRecordSet": .})}'
      > remove-record.json
    - aws --region eu-west-1 route53 change-resource-record-sets --hosted-zone-id Z072013523EW763CDQ8K4 --change-batch file://remove-record.json || true

build production docker image:
  extends: build docker image
  only:
    - tags
  except:
    - master
  after_script:
    - docker tag $DOCKER_TAG $DOCKER_TAG_PRODUCTION
    - docker tag $DOCKER_TAG $DOCKER_LATEST
    - docker push $DOCKER_TAG_PRODUCTION
    - docker push $DOCKER_LATEST    
  variables:
    DOCKER_TAG_PRODUCTION: registry.hub.docker.com/thalia/concrexit:$CI_COMMIT_TAG
    DEV_REQUIREMENTS: 0

cache:
  key: "$CI_JOB_NAME"
  paths:
    - "${PIP_CACHE_DIR}"

# vim: set sw=2 ts=2 et :
