version: '3.5'

services:
    postgres:
        image: postgres:11.1
        volumes:
            - /var/lib/postgresql/
        environment: &postgresvars
            POSTGRES_DB: thalia
    web:
        image: registry.hub.docker.com/thalia/concrexit
        build: .
        command: runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on:
            - postgres
        volumes:
            - ./website:/usr/src/app/website/
            - concrexit:/concrexit/
        environment: &webvars
            <<: *postgresvars
            DJANGO_DEBUG: 'True'
            DJANGO_POSTGRES_HOST: postgres

volumes:
    concrexit:
        driver: local
